language: java
dist: trusty
sudo: false
jdk:
  - openjdk8
before_install:
  - chmod +x ./gradlew
install:
  - ./gradlew assemble -Pjacoco
before_script:
  - chmod +x ./gradlew
script:
  - ./gradlew check -Pjacoco
  - ./gradlew :codeCoverageReport -Pjacoco
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
# Maven: install: mvn -Psvg,tutorial,svm,uncertain -DskipTests=true -Dmaven.javadoc.skip=true -B -V clean install
# Maven: script: mvn -Pcodecov -DskipTests=false -Dmaven.javadoc.skip=true -B -V test
# Maven: before_install: pip install --user codecov
# Maven: after_success: codecov

